### ZDNET KOREA 사이트의 뉴스 제목, 주소를 수집하여 DataFrame으로 만들어보기

사이트 주소 :

1. url 주소의 pageno를 이용하여 1~20 페이지 문서 요청
2. 응답 받은 웹 문서를 변환하기
3. 변환된 웹 문서에서 뉴스의 제목, 주소(href) 수집 후 리스트로 저장
4. 리스트를 DataFrame으로 생성 후 저장

In [7]:
import requests as req
import pandas as pd
import time

from bs4 import BeautifulSoup as bs

In [9]:
news_selection_url = "https://search.zdnet.co.kr/?kwd=%EC%9D%8C%EC%8B%9D%EB%AC%BC"

res = req.get(news_selection_url)

html = bs(res.text, "lxml")

In [15]:
# 연관된 정보를 가져올때는 a 태그 
news_list = html.select("div.assetText a")
news_list

[<a href="https://zdnet.co.kr/view/?no=20250107103541">
 <!--<h3>[1분건강] 백신없는 노로바이러스감염증, 손씻기가 최선 예방법<br>code11=0100<br>code12=0058<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>[1분건강] 백신없는 노로바이러스감염증, 손씻기가 최선 예방법</h3>
 <p>
 					예방백신이 없는 노로바이러스(Norovirus) 감염증, 손씻기 등 개인위생 수칙을 통한 예방이 권고된다. 노로바이러스감염증은 11월~3월 겨울철에 주로 발생한다. 개인위생이 취약하고 집단생활을 많이 하는 0세~6세를 중심으로 발생한다. 노로바이러스는 감염력이 강하고, 일상 환경에서도 사흘간 생존이 가능하며, 면역을 유지하는 기간이 짧아 과거에 걸렸던 사람도 재감염될 수 있다. 감염경로는 노로바이러스에 오염된 물이나 <mark>음식물</mark>을 섭취한 경우다. 그렇지만 환자 접촉을 통한 사람 간 전파나 환자 분비물의 침방울에 의한 감염도 가능하다. 감염되면 12시간~48시간 안에 구토와 설사가 나타나며, 복통·오한·발열이 발생하기도 한다. 외출 후·식사 전·배변 후 30초 이상 흐르는 물에 비누로 손을 씻어야 한다. 식재료를 흐르는 물에 씻어 85℃ 이상에서 1분 이상 충분히 익혀야 한다. 채소·과일은 흐르는 물에 깨끗이 씻어 먹고, 껍질은 벗겨 먹자. 끓인 물을 마시자. 조리 시에는 칼과 도마는 소독해 사용하고, 조리도구는 채소용·고기용·생선용 등으로 구분해 사용해야 한다. 노로바이러스감염증 환자는 증상이 사라진 후 48시간까지 등원·등교·출근을 자제하고, 화장실을 비롯한 생활공간을 다른 가족과 구분해 생활해야 한다. 화장실 사용 시 배변 후 물을 내릴 때 변기 뚜껑을 닫아 비말로 인한 노로바이러스 확산을 차단하도록 해야 한다. 환자가 사용했던 공간이나 화장실, 환자 분비물에 오염된 물품은 시판용 락스를 희석해 묻힌 천으로 닦아내어 소독하자. 환자의 분비물을 제거할 때는 비말을 통해 감염되지 않도록 마스크와 장갑을 반드시 착용해야 한다. 소독은 손이 닿는 문 손잡이나 수도꼭지 등을 중심으로 닦아내야 한다. 세탁물은 70℃ 이상에서 빨거나, 락스 희석액에 5분 이상 헹궈야 한다. 지영미 질병청장은 “노로바이러스감염증을 예방하기 위해 올바른 손씻기 등 예방수칙 준수와 안전하게 조리한 음식 섭취를 해야 한다”라며 “영유아 보육시설에서는 유증상자 등원 자제와 환자 사용 공간 소독을 하고, 집단환자 발생 시 가까운 보건소로 신고해달라”라고 당부했다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20250106101226">
 <!--<h3>쿠쿠, 12개 품목 'E-순환우수제품' 인증<br>code11=0100<br>code12=0030<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>쿠쿠, 12개 품목 'E-순환우수제품' 인증</h3>
 <p>
 					종합 생활가전 기업 쿠쿠는 정수기, <mark>음식물</mark>처리기 품목 12개 모델이 'E-순환우수제품' 인증을 획득했다고 6일 밝혔다. E-순환우수제품은 전기·전자제품의 자원 순환성을 평가하고 인증하는 제도다. 국내 유일 폐전기·전자제품 재활용 공제조합이자 환경부 인가 비영리 공리법인인 'E-순환거버넌스'가 주관한다. 재활용 가능성과 유해 물질 함유 여부 등을 종합적으로 평가하는데, 쿠쿠는 지속 가능한 미래를 위한 친환경 기술과 혁신을 통해 이 기준을 충족했다. 쿠쿠 정수기 5개 모델은 '재활용 가능률'과 '분해 용이성' 항목에서 우수한 평가를 받았다. 최소 단위 부품까지 분해할 수 있도록 세밀하게 설계돼 정밀한 재질 분류가 가능한 점을 통해 재활용 효율을 극대화했다. 건조분쇄형 음식물처리기 4개 모델은 '플라스틱 재활용 용이성' 부문에서 높은 점수를 획득했다. 모든 플라스틱 부품이 단일 재질로 분리되도록 설계해 재활용이 용이하며, 고품질 재생 원료 생산이 가능하다. 또 다른 미생물형 음식물처리기 3개 모델은 플라스틱 부품의 약 3분의 1을 재생 플라스틱으로 제작해 '재활용 원료 함유율'에서 우수한 평가를 받았다. 쿠쿠는 2018년부터 생활가전제품에 재생 플라스틱 부품을 도입했다. 대형 생활가전제품의 내장재와 포장재에도 재생 플라스틱과 업사이클링 소재를 활용했다. 쿠쿠 관계자는 "이번 인증은 친환경 제품 개발이 지속 가능한 미래를 위한 필수 과정임을 확인하는 계기가 됐다"며 "앞으로도 ESG 경영을 기반으로 지속 가능한 기술과 제품을 선보이며 환경과 공존하는 기업으로서의 책임을 다할 것"이라고 말했다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20250102172215">
 <!--<h3>7일 개막 CES 핵심 키워드는...&quot;AI 세상으로 몰입하세요&quot;<br>code11=0100<br>code12=0030<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>7일 개막 CES 핵심 키워드는..."AI 세상으로 몰입하세요"</h3>
 <p>
 					세계 최대 가전·IT 전시회인 'CES 2025'가 오는 7일(현지시간)부터 10일까지 미국 라스베이거스에서 개최된다. 올해 CES는 한층 진화된 인공지능(AI) 기술이 적용된 가전, IT 전자기기, 소프트웨어, 모빌리티, 로봇, 디지털헬스, 푸드테크 등이 선보일 예정이다. 올해 새롭게 선보이는 주제로 양자컴퓨팅, 에너지 전환 기술도 주목된다. CES 2025는 '드라이브 인(Dive In)'을 주제로 총 160개 국가에서 4500개 기업이 참가한다. 우리나라는 삼성, LG, 현대, SK, 포스코, 롯데 등 주요 대기업을 포함해 역대 최대규모인 900여개사가 참가하며, 이는 미국, 중국에 이어 세번째로 많은 규모다. 산업통상자원부와 KOTRA는 역대 최대 규모인 '통합한국관'을 마련해 국내 445개 기업의 참가를 지원한다. 젠슨 황 엔비디아 CEO 기조연설서 'AI 시대 혁신' 제시 기조연설을 통해 올해의 CES 주제를 한 눈에 볼 수 있다. 올해 CES 기조연설의 화두는 AI에 초점이 맞춰졌다. AI 시대를 이끄는 엔비디아의 젠슨 황 CEO가 개막 전날인 6일 오프닝 기조연설을 맡았다. 황 CEO는 AI 칩 블랙웰 등의 진행 상황을 공유하고, AI 컴퓨팅 시대의 트렌드를 공유할 예정이다. 그 밖에 델타항공의 에드 바스티안 CEO는 항공산업의 변화와 혁신 전략을 발표할 예정이다. 에드 CEO의 기조연설은 역대 CES 중 최초로 라스베이거스 대형 공연장인 '스피어'에서 진행될 예정이어서 주목된다. 마틴 룬드스테드 볼보 CEO는 전기 배터리, 수소 연료 전지 등을 통해 화석 연료 없는 운송 시스템을 소개한다. 유키 쿠수미 파나소닉 CEO는 AI를 통해 가족, 개인, 사회의 안전함을 증진시키는 혁신을 발표할 예정이다. 삼성·LG전자, AI로 일상을 바꿔주는 '스마트 홈' 가전 가전 분야에서는 삼성전자와 LG전자를 비롯해 TCL, 하이센 등 중국 기업들이 대규모 부스를 마련하고 AI 가전 체험존을 선보인다. AI 가전은 이전 보다 더 큰 스크린 탑재로 AI 기능의 편의성을 높이고, 온디바이스 AI 기능을 강화한 점이 특징이다. 삼성전자는 9형 터치스크린을 탑재한 비스포크 냉장고와 7형 터치스크린을 탑재한 비스포크 세탁기와 건조기 등 스크린 기반의 'AI 홈' 가전을 선보일 예정이다. 넓은 스크린으로 집안의 연결된 가전을 한눈에 보여주는 '맵 뷰(Map view)'를 지원하고, 연결된 가전의 전원을 켜고 끌 수 있다. 또 삼성전자는 '가정용 히트펌프 EHS' 제품을 이번 CES에서 공개한다. 이미 유럽 40개 국가에서 판매하고 있는 이 제품을 올해부터 미국 공조 시장에서 적극 공략한다는 계획이다. 아울러 AI 기능이 향상된 2025년형 스마트 모니터 32형 'M9'와 3D 전용 안경 없이도 3차원 경험을 제공하는 27형 게이밍 모니터 '오디세이 3D'를 비롯해 신제품 모니터 5종을 전시한다. LG전자는 AI 기능을 강화한 초프리미엄 가전 'LG 시그니처' 신제품을 CES에서 공개한다. '스마트 인스타뷰 냉장고'는 투명 올레드 기술과 AI기반 식재료 관리 솔루션을 결합한 제품이다. 문을 열지 않고도 <mark>음식물</mark>의 종류와 양을 확인할 수 있는 인스타뷰 기술은 투명 올레드 디스플레이를 만나 한층 업그레이드됐다. '인덕션 더블 오븐 슬라이드인 레인지'는 내부 카메라로 음식물을 인식해 메뉴를 추천해 주는 고메AI(Gourmet AI) 기술이 적용됐다. '후드 겸용 전자레인지'는 전면에 달린 27인치 LCD 화면을 통해 조리 과정을 실시간으로 볼 수 있다. 또 LG전자는 이번 CES에서 식물생활가전 '틔운'의 새로운 컨셉을 첫 공개할 예정이다. 새로운 틔운은 스탠드 조명과 블루투스 스피커가 내장된 협탁 디자인으로 식물을 키울뿐 아니라 가전제품으로 활용할 수 있어 혁신을 이뤘다. 아울러 LG전자는 업계 최초로 5K2K 해상도(5,120X2,160)를 지원하는 OLED 게이밍 모니터 '45형 울트라기어 모니터' 2종 (모델명: 45GX990A/950A)을 공개한다. 삼성전자와 LG전자는 CES 미디어 데이 컨퍼런스에서 나란히 기조연설을 발표해 주목된다. 한종희 삼성전자 DX부문 부회장은 6일 오후 2시(현지시간) 'AI for All: Everyday, Everywhere(모두를 위한 AI: 경험과 혁신의 확장)'라는 주제로 삼성전자의 홈 AI 전략을 발표할 예정이다. 조주완 LG전자 CEO도 같은날 오전 8시 '공감지능과 함께하는 일상의라이프스 굿(Life's Good 24/7 with Affectionate Intelligence)'를 주제로 스마트라이프 솔루션으로 변모하는 LG전자의 전략을 공개한다. ■ 모빌리티 SDV 기술 선봬...현대모비스·하만·LG전자 참가 모빌리티 분야에서는 '소프트웨어 중심 자동차(SDV : Software Defined Vehicle)'를 화두로 자율주행과 인포테인먼트 분야에서 혁신을 이루는 기술을 공개한다. 현대차그룹에서 유일하게 부스를 꾸린 현대모비스는 'Beyond and More' 주제로 사람과 교감·소통하는 휴먼 테크를 선보인다. 또 윈드실드에 홀로그래픽을 기반으로 구성되는 디스플레이와 뇌파를 기반으로 운전자 부주의 상황을 모니터링하는 기술들도 기대된다. LG전자 VS사업본부와 삼성전자 하만은 CES 관람객 대상으로 처음으로 참가하며 모빌리티 기술을 알린다. 양사는 기존에 완성차 고객 대상으로 비공개 부스만 운영해 왔다. LG전자는 인캐빈 센싱 솔루션을 주력으로 소개한다. 인캐빈 센싱 솔루션은 카메라와 센서 등으로 차량 내부를 감지∙분석해 교통사고도 예방하는 기술이다. LG전자는 AI 반도체 전문기업 암바렐라(Ambarella)와 협력해 인캐빈 센싱 솔루션 성능을 더욱 향상시켰다고 밝혔다. 해당 기술은 CES 암바렐라 부스에서도 선보일 예정이다. LG이노텍은 미래 모빌리티를 주제로 센싱, 통신, 조명, 제어 기술력을 활용한 미래 모빌리티 부품 41종의 실물을 공개할 계획이다. 삼성전자 하만은 별도의 부스를 마련했다. 하만은 최근 출시한 차량용 소프트웨어 '레디 시퀀스 루프'와 '레디 링크 마켓플레이스' 등을 CES에서 소개할 전망이다. 또 하만은 증강현실 기반의 헤드업 디스플레이 제품인 '레디 비전'의 신버전 등도 선보일 계획이다. 일본 도요타는 5년 만에 CES에 참가해 모빌리티 업계의 관심을 모으고 있다. 도요타는 '우븐시티'를 통해 수소 연료 생태계와 자율주행차 등 첨단 모빌리티 솔루션을 공개할 예정이다. 도요타는 5년전 CE에서 처음으로 우븐시티를 발표한 바 있다. 그 밖에 미국의 특수차량 제조회사 '오시코시 코퍼레이션'이 CES에 처음으로 참가한다. 반도체, 로봇, 푸드테크, 헬스케어 등 전 산업에 AI 확산 로봇, XR(확장현실), 푸드테크, 헬스케어, 에듀테크, 금융 등 전 산업에 AI 기능이 중요해졌다. 헬스케어 분야에서는 AI로 건강관리와 일상생활이 편리해지는 기술이 전시될 예정이다. 로봇 분에서는 가정용 로봇, 헬스로봇, 휴머노이드 기술이 주목받는다. SK그룹은 '혁신적인 AI 기술이 지속 가능한 미래를 만든다'는 주제로 SK텔레콤, SK하이닉스, SKC, SK엔무브 등이 공동 전시관을 꾸린다. SK그룹 전시관의 핵심은 'AI 데이터센터(AIDC)'다. SK그룹은 AIDC 부스 중앙에 AIDC의 데이터 흐름을 표현한 6m 높이 대형 LED 기둥을 설치하고, 데이터센터 내 발전원을 통해 안정적으로 전력을 공급하는 기술인 'AI 파워 오퍼레이터'와 액체를 활용한 발열 관리 기술인 '액체 냉각' 등 AIDC 솔루션을 선보인다. 또 SK텔레콤은 글로벌향 AI 에이전트 '에스터(Aster)'의 서비스 계획을 발표하고, SK하이닉스는 AI 반도체와 AI 데이터 솔루션을 포함한 고대역폭 메모리(HBM) 기술을 전시할 예정이다. SK텔레콤은 AI 기반 모바일 금융사기 탐지·방지 기술인 '스캠뱅가드'로 CES 최고 혁신상을 수상했다. 롯데그룹은 정보기술(IT) 계열사 롯데이노베이트는 혼합현실(MR)과 확장현실(XR) 기반의 메타버스 서비스인 '칼리버스'의 세계관과 콘텐츠를 공개한다. 세라젬, 바디프랜드 등도 AI 기능을 강화한 안마의자를 선보일 예정이다. 디지털 헬스케어 분야에서는 마인드허브, 잼잼테라퓨틱스, 라이덕, 오렌지바이오메드, 팀엘리시움 등 스타트업이 참가해 헬스케어 기술을 선보인다. 한편, 올해 CES 혁신상 수상기업 전체 292개사 중 우리나라 기업은 129개사로 작년에 이어 최다 수상을 달성하며 기술력을 입증했다. 웅진씽크빅의 다양한 성우 목소리로 책을 읽어주는 AI 독서 플랫폼 '북스토리', 국내 핀테크 스타트업 고스트패스의 온디바이스AI 기반 생체인증 결제솔루션 등이 최고혁신상을 받았다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241230085447">
 <!--<h3>LG전자, CES 2025서 프리미엄 가전 '시그니처' 신제품 공개<br>code11=0100<br>code12=0030<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>LG전자, CES 2025서 프리미엄 가전 '시그니처' 신제품 공개</h3>
 <p>
 					LG전자가 AI기술을 적용한 초프리미엄 주방 가전 'LG 시그니처' 냉장고·식기세척기 신제품을 CES 2025에서 공개한다. LG전자는 내달 8일(현지시간) 미국 라스베이거스에서 열리는 세계 최대 가전·IT 전시회 CES 2025에 LG 시그니처존을 마련한다. LG 시그니처는 ▲기술 혁신으로 이룬 압도적인 성능 ▲본질에 충실한 정제된 디자인 ▲지금까지 경험해 보지 못한 직관적인 사용성을 지향하는 초프리미엄 가전제품을 아우르는 통합 브랜드다. LG전자는 이번에 공개하는 LG 시그니처 제품에 세월이 흘러도 변하지 않는 본질적 가치를 극대화하는 고품격 디자인과 AI기술을 반영했다. '스마트 인스타뷰 냉장고'는 투명 올레드 기술과 AI기반 식재료 관리 솔루션을 결합해 글로벌 초프리미엄 가전 시장에 혁신을 제시한다. 문을 열지 않고도 <mark>음식물</mark>의 종류와 양을 확인할 수 있는 인스타뷰 기술은 투명 올레드 디스플레이를 만나 한층 업그레이드됐다. 투명 올레드 디스플레이에 평상 시 표출되는 커버 스크린은 주변 인테리어와 조화를 이루며 공간을 더욱 세련되게 만든다. 고객은 원하는 사진을 액자처럼 띄워놓거나 제공된 영상을 재생시켜 주방을 새로운 분위기로 연출할 수 있다. 스마트 인스타뷰 냉장고의 AI관리 솔루션은 식재료 관리의 번거로움을 해결한다. AI가 내부 카메라로 냉장고에 들어오고 나가는 식품을 자동으로 인식하며, 연동된 LG 씽큐 푸드 앱을 통해 보관 목록과 위치까지 보여준다. '식기세척기'에는 '팝아웃 핸들' 기능이 적용됐다. 평소에는 외부로 돌출되는 부분이 없다가 사용자의 손이 가까이 다가오면 핸들이 자동으로 올라오는 구조로, 미니멀한 디자인이 고급스러움을 극대화한다. 도서관에서 조용히 대화하는 수준의 초저소음을 구현한 점이 특징이다. '인덕션 더블 오븐 슬라이드인 레인지'에는 내부 카메라로 음식물을 인식해 메뉴를 추천해 주는 고메AI(Gourmet AI) 기술이 적용됐다. 바게트와 크로와상, 머핀 등 베이커리 3종은 고객이 굽기 정도를 선택하면 AI가 요리의 상태를 파악해 AI브라우닝 알림을 보내기 때문에 고객은 입맛에 맞는 요리를 손쉽게 완성할 수 있다. '후드 겸용 전자레인지'는 전면에 달린 27인치 LCD 화면을 통해 조리 과정을 실시간으로 볼 수 있다. 고객이 시그니처 전자레인지와 오븐을 서로 연동하면, 인덕션 더블 오븐 슬라이드인 레인지의 조리 상황을 전자레인지의 디스플레이로 허리를 굽히지 않고 모니터링이 가능하다. LG전자 전시장 방문 고객은 ▲29인치 세탁기와 건조기 ▲7인치 터치 LCD를 적용한 세탁건조기 등 혁신적인 LG 시그니처 제품들을 경험할 수 있다. LG전자 HS사업본부장 류재철 사장은 “새로운 LG 시그니처 라인업은 기술 혁신과 세련된 디자인으로 초프리미엄 가전의 새로운 기준을 제시한다”며 “고객의 일상을 특별하고 가치 있게 만드는 LG 시그니처를 앞세워 글로벌 시장에서 차별화된 고객 경험을 제공할 것”이라고 말했다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241226154137">
 <!--<h3>환경부, 순환경제 신기술·서비스 9건 규제박스 특례<br>code11=0100<br>code12=0075<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>환경부, 순환경제 신기술·서비스 9건 규제박스 특례</h3>
 <p>
 					환경부는 올해 순환경제 규제특례(샌드박스) 제도를 도입해 폐배터리 재활용 기술·농업부산물 활용 연료생산 등 총 9건의 폐자원 활용 신기술·서비스에 특례를 부여했다고 26일 밝혔다. 샌드박스 제도는 한정된 기간·장소·규모에서 새로운 기술과 서비스로 실증테스트를 허용하고, 안전성과 유효성이 입증되면 관련 규제를 개선하거나 보완하는 제도다. 순환경제 규제특례는 '순환경제사회 전환 촉진법' 시행에 따라 스마트시티·정보통신융합 등 분야에 이어 8번째로 도입됐다. 올해 승인된 순환경제 분야 신기술·서비스 9건은 ▲태양광 폐패널 현장 재활용(1건) ▲생분해 플라스틱 바이오가스화(2건) ▲이차전지(폐배터리) 재활용 및 재생산 기술(2건) ▲농업부산물(양파박) 사료화(1건) ▲슬러지 및 가축분뇨를 활용한 고체연료 생산 실증(2건) 등이다. '태양광 폐패널의 현장 재활용 서비스(원광에스앤티)'는 컨테이너 탑재형 장비를 활용해 현장에서 폐패널을 재질별로 분리 운송, 유용자원을 회수하는 공정을 실증하는 사업이다. 그간에는 이동식 폐기물처리시설 설치기준이나 처리업 인허가 기준이 없어 시행할 수 없었다. 상용화하면 태양광 폐패널의 운송부피를 획기적으로 줄여, 배출자 운송비 부담을 경감해 폐패널 방치를 예방하고 유용자원 회수율을 높이는 등 재활용이 촉진될 것으로 기대된다. '생분해성 플라스틱 통합바이오가스화 실증(한국플라스틱협동조합·한국바이오플라스틱협회)'은 생분해성플라스틱 제품(봉투나 용기 등)을 <mark>음식물</mark>과 함께 통합 바이오가스시설에 혼입해 가스 생성률·적정 수거체계 등을 실증하는 사업이다. 현행 법령은 음식물·하수찌꺼기 등 지정된 유기성 폐자원이 아닌 생분해성 플라스틱은 통합바이오가스화시설에 투입할 수 없다. 희소금속을 다량 함유한 폐배터리 재활용 분야는 규제특례 대상으로 부각받고 있다. 이를 친환경적으로 추출할 수 있는 신기술은 핵심 광물 공급 안정화와 재생원료 사용 의무화 같은 '친환경 장벽'에 대응하기 위해 국내 산업 경쟁력 확보 차원에서도 중요하기 때문에 환경부는 이차전지(폐배터리) 재활용 및 재생산 기술 2건의 특례 부여를 통해 적극 지원하기로 했다. '저온처리 직접재활용 방식의 폐배터리 재활용 및 재생산 기술(리셀K1)'은 폐배터리를 저온(400도)에서 전처리한 후, 수처리만으로 니켈(Ni)·코발트(Co)·리튬(Li) 등 금속을 추출하고 황산염 환원 박테리아를 활용해 전구체 복합액을 재생산한다. 이 기술이 실용화되면 에너지 소모를 획기적으로 줄일 수 있고, 금속추출 과정에서 황산을 사용하지 않기 때문에 황산을 포함한 오·폐수가 발생하지 않는다. '이차전지 공정 부산물에 직접재활용 기술을 적용한 양극재·음극재 재제조(에이비알)' 사업은 사용후 배터리가 아닌 제조과정에서 발생하는 이차전지 공정 부산물을 저온처리 후, 물과 물리적 방법만을 사용해 양극과 음극 활물질(Active material)을 회수하고, 양극재·음극재로 제품화하는 기술이다. 환경부는 순환경제 규제특례(샌드박스) 제도 첫 시행인 만큼 간담회 등을 통해 기업 애로 사항을 청취하고, 상담을 실시하는 등 산업계 참여를 이끌었다. 올해 11월까지 176건의 기업상담을 실시해 발굴된 47건(승인 9건 포함)의 사업과제도 현재 검토 중에 있다. 새해에는 개별 기업 신청으로 발굴된 과제뿐만 아니라 정부가 직접 핵심 순환자원을 먼저 찾아내고, 이후에 이를 실증할 사업자를 모집하는 기획형 규제특례(샌드박스) 제도가 새롭게 도입될 예정이다. 김호은 환경부 자원순환정책과장은 “기후변화 대응과 탄소중립을 위해서는 제품의 지속가능성을 높이고 자원순환망을 구축, 자원과 에너지를 최소화하는 친환경 순환경제 체계가 필수적인 조건”이라면서 “산업이 빠르게 창출되는 상황에서 신기술·서비스가 모호하거나 불합리한 규제에 막히는 일이 없도록 과감히 도전하는 기업에 현실적인 도움을 줄 수 있도록 적극 지원할 것”이라고 말했다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241220193857">
 <!--<h3>스마트카라, '나폴리 맛피아'와 쿠킹 클래스<br>code11=0100<br>code12=0030<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>스마트카라, '나폴리 맛피아'와 쿠킹 클래스</h3>
 <p>
 					스마트카라는 넷플릭스 요리 경연 프로그램 흑백요리사 우승자인 '나폴리 맛피아' 권성준 셰프와 함께 진행한 쿠킹 클래스 행사를 진행했다고 20일 밝혔다. 스마트카라는 고객들이 그간 보내준 사랑에 보답하고자 스마트카라 구매 고객을 위한 특별 이벤트로 이번 쿠킹 클래스를 기획했다. 쿠킹 클래스는 지난 14일 쿠킹 스튜디오 '라퀴진 한남'에서 진행됐다. 신청자 중 추첨을 통해 선발된 고객 10명이 참가했다. 로맨틱 연말 디너 컨셉으로 진행된 쿠킹 클래스에서는 참가자들이 권성준 셰프의 레시피를 직접 배워보고 쿠킹 체험까지 실습하는 시간을 가졌다. 쿠킹 클래스에서 선보인 메뉴는 '송아지 갈비찜과 샤프론 리조또', '피스타치오 딸기 티라미수'로 구성됐다. 쿠킹 클래스 이후 발생한 <mark>음식물</mark>쓰레기는 스마트카라 '블레이드X'로 처리했다. 제품은 5L 대용량 제품으로 업계 최초로 표준모드와 강력모드 두 가지 모드로 사용 가능한 듀얼 처리모드를 적용한 음식물처리기다. 강력모드 사용 시 기존 음식물처리기로는 처리할 수 없었던 치킨 뼈나 게 껍데기와 같은 딱딱한 부산물도 처리가 가능할 수 있다. 처리 시간은 평균 2시간 30분~4시간이 걸린다. 에코필터도 기존 모델 대비 성능이 125% 향상됐다. 권성준 셰프는 "치킨을 좋아해 자주 먹는 편인데 '블레이드X'의 강력모드를 활용해 처치 곤란했던 치킨 뼈까지 바로 처리할 수 있어 매우 편리하다"고 말했다. 스마트카라 관계자는 "앞으로도 음식물처리기 리딩 기업으로서 고객과의 접점을 넓힐 수 있는 다채로운 이벤트를 지속적으로 마련해갈 예정"이라고 말했다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241210232634">
 <!--<h3>스마트카라, <mark>음식물</mark>처리기 보상판매…최대 54만원 할인<br>code11=0100<br>code12=0030<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>스마트카라, <mark>음식물</mark>처리기 보상판매…최대 54만원 할인</h3>
 <p>
 					스마트카라는 <mark>음식물</mark>처리기를 보상판매 프로모션을 진행한다고 10일 밝혔다. 스마트카라는 이번 프로모션에서 최대 54만원의 할인 혜택을 제공한다. 브랜드 상관없이 가정용 음식물처리기를 사용하던 고객이면 누구나 기존 제품을 반납하고 스마트카라 신제품 음식물처리기 2종을 할인가로 구매할 수 있다. 이번 프로모션은 스마트카라 공식 홈페이지에서 오는 22일까지 진행된다. 전자제품에 속하는 가정용 음식물처리기라면 고장·파손된 제품이라도 신청 가능하다. 제품별로 ▲블레이드X 45만원 ▲블레이드X 스토리지타워 패키지 53만원 ▲스마트카라 400 프로2 49만원 ▲스마트카라 400 프로2 스토리지타워 패키지 54만원 즉시 할인을 제공한다. 보상판매 할인 쿠폰은 발급일로부터 7일 동안 유효하다. 보상판매 신청은 한정 수량으로 진행되며 계정당 한 개의 제품만 신청할 수 있다. 혜택가가 적용된 상품을 구매한 후 영업일 기준 1~3일 이내 기존 제품을 회수하는 방식으로 진행된다. 구매 고객 전원 대상 추가 사은품도 마련했다. 블레이드X 구매 고객에게는 에코필터 1세트를, 스마트카라 400 프로2 구매 고객에게는 리필필터 카트리지 1세트를 추가 증정한다. 한편 스마트카라는 2021년부터 보상판매 프로모션을 진행해왔다. 지난 7월에도 해당 프로모션을 진행한 바 있다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241208102041">
 <!--<h3>제4회 팩트체크 전국대회 시상식 열려...총 15점 수상<br>code11=0100<br>code12=0010<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>제4회 팩트체크 전국대회 시상식 열려...총 15점 수상</h3>
 <p>
 					방송통신위원회가 주최하고 시청자미디어재단이 주관하는 제4회 팩트체크 전국대회시상식이 지난 7일 스페이스쉐어 서울중부센터에서 개최됐다. 올해 대회는 가짜뉴스와 딥페이크 등 미디어역기능이 전 세계적으로 심각한 문제가 되고 있는 가운데 경제 사회 문화 분야에서 사실(fact) 확인이 필요한 정보를 시민들이 직접 선정하고 검증했다. 청소년부 대상은 한국의 <mark>음식물</mark> 쓰레기 자원화 여부를 다양한 논문을 통해 교차 검증한 안양 충훈고등학교 '두더지' 팀, 일반부 대상은 수입쌀의 과잉 공급으로 쌀값이 폭락했다는 주장의 사실 여부를 정보공개 청구와 전문가 인터뷰 등을 통해 검증한 중앙대학교 '딥트루' 팀이 수상했다. 최우수상은 울산고운중학교 '고운탐정수사대' 팀의 '파란펜으로 공부하면 학습에 도움이 될까?', 대전동화중학교 '팩트나침반' 팀의 '인스타그램 이벤트의 올바른 나침반을 만들자!', 아주대학교 'SOS' 팀의 '성공하고 싶으면 서울로 가라는 말은 옛말일까?'가 차지했다. 본선 경연은 공모를 통해 신청한 64개 팀들 중 선발된 25개 팀이 최종결과물을 발표하는 행사로 이뤄졌으며, 현장 심사를 통해 대상 2팀(방송통신위원장상), 최우수상 3팀, 우수상 3팀, 장려상 7팀(이상 시청자미디어재단 이사장상)이 선정됐다. 심사위원장을 맡은 지연옥 대진대 부총장은 “전문가 멘토링을 거쳐 올라온 최종 결과물의 완성도가 모두 높아 본선 팀들 간 우열을 가리기가 힘들었으며, 청소년부와 일반부 모두 평범한 일상 속에서 느끼는 작은 문제의식들을 주제로 선정해, 논리적으로 사실여부를 밝혀냈다”고 평했다. 최철호 시청자미디어재단 이사장은 “이번 전국대회는 저출생, 지구 온난화, 대학 등록금, 국내산 소고기 등 생활 속에서 쉽게 접할 수 있는 소재들이 팩트체크 대상으로 활용된 점이 특징”이며 “참가자들이 통계의 교차 확인, 설문조사, 전문가 인터뷰 등의 과정을 거쳐 기존 상식과 사회적 통념을 다시 따져보며 의미 있는 결과들이 나왔다”고 밝혔다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241205114605">
 <!--<h3>쿠쿠전자, 전자레인지 신제품 출시<br>code11=0100<br>code12=0030<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>쿠쿠전자, 전자레인지 신제품 출시</h3>
 <p>
 					종합 생활가전 기업 쿠쿠전자는 미니멀리즘 트렌드에 맞는 콤팩트한 외형에 다이얼 조작으로 누구나 쉽게 사용할 수 있는 전자레인지를 출시한다고 5일 밝혔다. 쿠쿠 전자레인지는 외형을 콤팩트하게 유지하되, 내부 조리실을 넓게 제작하여 최대 20L까지 수용 가능한 넉넉한 조리 공간을 마련했다. 제품 전면부에 장착된 조그 다이얼을 통해 동작 시간을 빠르고 편리하게 선택 가능하다. 복잡한 기능과 버튼을 단순화하여 직관적으로 표현해 남녀노소 누구나 쉽게 조작할 수 있다. 최대 700W 고주파를 출력한다. 디자인은 밝은 화이트 색상과 부드러운 곡선이 특징이다. 손쉽게 한층 세련된 주방 분위기 연출이 가능하다. 일체형 디자인으로 핸들이 돌출되지 않아 좁은 공간에서도 효율적으로 사용할 수 있는 것 또한 장점이다. 위생도 꼼꼼하게 고려했다. 화이트 클린 코팅을 통해 기름때나 조리 중 흐른 <mark>음식물</mark>이 스며들기 어렵고 쉽게 닦아낼 수 있다. 틈새가 적은 일체형 도어 핸들로, 오염이 적고 청소가 간편해 변색 없이 오래도록 청결하게 사용이 가능하다. 제품은 회전형과 플랫 타입 두 가지 모델로 구성됐다. 플랫 타입의 경우 바닥 전체에서 고주파가 배출돼 사각지대 없이 구석구석 균일하게 열전달이 가능하다. 모든 내부 공간을 활용할 수 있어 대형 식기뿐 아니라 두 가지 요리도 한 번에 조리할 수 있다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241129173530">
 <!--<h3>휴롬, 연말 프로모션…착즙기 최대 26% 할인<br>code11=0100<br>code12=0030<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>휴롬, 연말 프로모션…착즙기 최대 26% 할인</h3>
 <p>
 					휴롬은 연말 쇼핑시즌을 맞아 오는 12월 11일까지 온오프라인 채널에서 '그린 프라이데이' 프로모션을 진행한다고 29일 밝혔다. 휴롬 공식몰에서는 최신형 프리미엄 착즙기 H410 제품을 26% 할인된 36만9천원에 선보인다. 공식몰 단독으로 H410 착즙기와 휴롬 파워블렌더 세트를 39만9천원에 구매할 수 있다. 또한 착즙기 외에도 <mark>음식물</mark>처리기, 티마스터 등 휴롬 제품들을 최대 46% 할인가에 만날 수 있다. 세척과 손질이 완료되어 착즙기에 넣기만 하면 건강주스를 손쉽게 즐길 수 있는 휴롬 주스키트 스타터키트를 하루 100명 선착순으로 42% 할인가에 제공한다. 공식몰 라이브 방송은 내달 5일과 8일 진행될 예정이다. 라방 구매 시 H410 제품 1만원 추가 할인 혜택과 함께 구매 인증 고객 10명을 선정해 요아이 두유제조기를 증정한다. 퀴즈왕 1명에게는 추첨을 통해 H410 구매 금액 전액을 환불해준다. 이와 함께 네이버 신상위크 기획전도 동시에 진행되며, H410 착즙기와 휴롬 주스키트 스타터키트를 함께 즐길 수 있는 세트 구성으로 39만9천원에 구매할 수 있다. 또한 주스키트 스타터키트도 하루 100명 선착순으로 1만9천9백원에 제공한다. 네이버 라이브방송은 2일과 11일에 진행된다. 라방 구매 시 H410 착즙기 1만원 추가 할인과 함께 구매 인증 고객 10명을 선정해 네이버페이 포인트 5만원을, 소통왕 10명을 선정해 네이버페이 포인트 5천원을 증정한다. 이 외에도 쿠팡, 11번가 등 온오프라인 채널에서도 해당 기간 동안 할인을 제공할 예정이다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241129002715">
 <!--<h3>산정특례 적용 희귀질환 1314개로 늘어…'이완불능증' 등 66개 추가<br>code11=0100<br>code12=0058<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>산정특례 적용 희귀질환 1314개로 늘어…'이완불능증' 등 66개 추가</h3>
 <p>
 					산정특례 대상으로 66개 희귀질환이 추가된다. 또 폐색성 비대성 심근병증 치료제 '캄지오스'와 신경모세포종 치료제 '콰지바주'는 건강보험급여가 적용된다. 보건복지부는 28일 2024년 제23차 건강보험정책심의위원회(이하 건정심)를 열고 ▲약제급여목록 및 급여상한금액표 개정(신약 등재)을 의결하고 ▲산정특례 대상 희귀질환 확대 등을 논의했다. 이날 건정심에서는 희귀질환관리법에 따라 국가관리대상 희귀질환으로 신규 지정된 '이완불능증'(식도 연동운동이 감소하거나 하부식도 괄약근 이완에 문제가 생겨 <mark>음식물</mark>이 내려가지 못하는 질환)을 비롯해 희귀질환 2개, 극희귀질환(유병 인구 200명 이하) 59개, 기타염색체이상질환 5개 등 66개 휘귀질환에 대해서도 산정특례를 적용키로 했다. 이에 따라 산정특례 대상 희귀질환은 1천248개에서 1천314개로 확대된다. 건강보험 본인일부부담금 산정특례제도는 의료비 부담이 큰 암 등 중증질환자, 희귀·중증난치질환자의 의료비 부담을 완화하기 위해 환자 본인이 부담하는 비용(본인부담률 입원 20%, 외래 30%∼60% → 산정특례 시 입원·외래 0%∼10% 적용)을 낮춰주는 제도이다. 이번에 신규 지정된 희귀질환에 대한 산정특례 확대는 관련 고시 개정 등을 거쳐 2025년 1월부터 적용될 예정이다. 한편 이날 건정심에서는 2024년 12월1일부터 폐색성 비대성 심근병증 환자의 운동 기능 및 증상 개선을 위한 치료제인 한국비엠에스제약 '캄지오스'(주성분: 마바캄텐)에 대해 건강보험(상한액 6만1619원)을 적용키로 했다. 그동안 폐색성 비대성 심근병증 환자의 증상 완화를 위해 고혈압, 부정맥 등에 사용되는 치료제(베타차단제, 칼슘채널차단제) 사용이 권고되어왔으나 효과가 없거나 부작용이 심한 환자들의 경우 치료에 어려움이 있었다. 해당 질환은 희귀질환자 산정특례 대상 질환으로 산정특례 대상자가 캄지오스(연간 1인당 투약비용 약 2249만원) 사용 시 본인부담금은 225만원(요양급여비용총액의 10% 적용)으로 낮아지게 된다. 이와 함께 신경모세포종 환자를 위한 치료제인 레코르다티코리아 '콰지바주'(주성분 : 디누툭시맙베타)도 건강보험(상한액 1148만2566원) 적용이 결정됐다. 신경모세포종 치료제는 '▲만 12개월에서 20세 미만의 이전에 ▲유도화학요법 이후 부분반응 이상을 보인 후 ▲조혈모세포이식을 받은 이력이 있는 신경모세포종, 재발성 혹은 불응성 신경모세포종'에서 급여가 가능하도록 급여기준이 설정됐다. 신경모세포종 환자는 1인당 연간 투약비용 약 3억5000만원을 부담했으나, 12월1일부터 건강보험이 적용되면 연간 투약비용이 약 1050만원(본인부담 5%, 본인부담상한제 적용 시) 수준으로 줄게 된다. 특히 콰지바주는 중증질환 치료제의 신속한 등재를 지원하기 위해 식품의약품안전처 허가와 동시에 건강보험심사평가원 급여평가 및 국민건강보험공단 협상까지 동시에 진행하는 '허가-평가-협상 병행 시범사업' 약제로 선정돼 식품의약품안전처 허가 후 5.5개월 만에 등재됐다. 관련해 보건복지부는 최근 2차 시범사업 수요조사를 완료했으며, 연내 대상 약제 선정 후 시범사업을 추진할 예정이다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241122173007">
 <!--<h3>익히지 않은 어패류에서 노로바이러스 식중독 발생 우려<br>code11=0100<br>code12=0058<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>익히지 않은 어패류에서 노로바이러스 식중독 발생 우려</h3>
 <p>
 					겨울철에도 식중독 위험이 있다. 특히 김장철 많이 사용하는 굴 등 어패류는 노로바이러스 식중독 발생 위험이 커 주의가 필요하다. 노로바이러스는 구토, 설사 등 급성 위장염을 일으키는 전염성이 강한 바이러스로 낮은 온도에서도 생존해 겨울철에 주로 발생한다. 최근 5년('19~'23)간 노로바이러스 식중독은 총 243건(환자수 4천279명)이 발생했으며, 월별 발생 추이를 분석한 결과 12월부터 이듬해 2월까지 발생한 식중독 건수는 119건으로 전체 식중독 건수의 약 49%가 겨울철에 발생한 것으로 나타났다. 노로바이러스 식중독이 가장 많이 발생한 장소는 학교‧어린이집 등 집단급식소이며 그 외에는 음식점, 가정 순으로 나타났다. 일반적으로 노로바이러스 감염은 노로바이러스에 오염된 <mark>음식물</mark>이나 지하수를 섭취해 발생하거나 환자의 분변과 구토물, 침, 오염된 손 등 사람 간 접촉으로 전파되는 것으로 알려져 있다. 식품으로 인한 노로바이러스 감염의 주요 원인은 생굴 등 익히지 않은 어패류로 굴 제품 포장에 '가열조리용', '익혀 먹는' 등의 표시가 있으면 반드시 중심 온도 85℃, 1분 이상 가열해 섭취해야 한다. 또 지하수는 정기적인 수질 검사를 통해 노로바이러스 오염 여부를 확인해야 하고 오염이 의심되는 경우 반드시 끓여서 섭취하는 것이 좋다. 사람 간 접촉으로 인한 노로바이러스 감염을 예방하기 위해서는 비누를 이용해 흐르는 물에 30초 이상 손 씻기 등 개인위생 관리를 철저히 하는 것이 중요하다. 학교‧어린이집 등에서 노로바이러스 감염 의심 증상이 있는 사람은 조리 등에 참여하지 않아야 하고 증상이 회복된 후에도 2~3일간은 휴식을 취해야 한다. 이와 함께 감염 환자의 구토물·분변 등을 처리한 주변이나 환자가 사용한 화장실‧문손잡이 등은 염소 소독제를 사용해 소독해야 한다.</p>
 </a>,
 <a href="https://zdnet.co.kr/view/?no=20241120132906">
 <!--<h3>케이블TV協, 3분기 지역채널 우수프로 8편 선정<br>code11=0100<br>code12=0010<br>code13=0010<br>code21=<br>code22=<br>code23=</h3>-->
 <h3>케이블TV協, 3분기 지역채널 우수프로 8편 선정</h3>
 <p>

In [19]:
a_list =[]
for i in news_list:
    a_list.append(i.get("href"))
a_list

['https://zdnet.co.kr/view/?no=20250107103541',
 'https://zdnet.co.kr/view/?no=20250106101226',
 'https://zdnet.co.kr/view/?no=20250102172215',
 'https://zdnet.co.kr/view/?no=20241230085447',
 'https://zdnet.co.kr/view/?no=20241226154137',
 'https://zdnet.co.kr/view/?no=20241220193857',
 'https://zdnet.co.kr/view/?no=20241210232634',
 'https://zdnet.co.kr/view/?no=20241208102041',
 'https://zdnet.co.kr/view/?no=20241205114605',
 'https://zdnet.co.kr/view/?no=20241129173530',
 'https://zdnet.co.kr/view/?no=20241129002715',
 'https://zdnet.co.kr/view/?no=20241122173007',
 'https://zdnet.co.kr/view/?no=20241120132906',
 'https://zdnet.co.kr/view/?no=20241119161715',
 'https://zdnet.co.kr/view/?no=20241115172948',
 'https://zdnet.co.kr/view/?no=20241113082353',
 'https://zdnet.co.kr/view/?no=20241112094650',
 'https://zdnet.co.kr/view/?no=20241111170209',
 'https://zdnet.co.kr/view/?no=20241107101852',
 'https://zdnet.co.kr/view/?no=20241016212046',
 'http://zdnet.co.kr/view/?no=20250104015036',
 'http://zdnet.co.kr/view/?no=20250107005122',
 'http://zdnet.co.kr/view/?no=20250106150953',
 'http://zdnet.co.kr/view/?no=20250106120252']

In [65]:
# 가져온 것의 제목, 주소 저장
data_list =[]

for href in a_list:
    res = req.get(href)
    html = bs(res.text, "lxml")

    # title과 href
    title = html.select_one("div.assetText > a > h3").text
    data_list.append([title, href])

AttributeError: 'NoneType' object has no attribute 'text'

In [27]:
data_list

[['[1분건강] 백신없는 노로바이러스감염증, 손씻기가 최선 예방법',
  'https://zdnet.co.kr/view/?no=20250107103541'],
 ["쿠쿠, 12개 품목 'E-순환우수제품' 인증", 'https://zdnet.co.kr/view/?no=20250106101226'],
 ['7일 개막 CES 핵심 키워드는..."AI 세상으로 몰입하세요"',
  'https://zdnet.co.kr/view/?no=20250102172215'],
 ["LG전자, CES 2025서 프리미엄 가전 '시그니처' 신제품 공개",
  'https://zdnet.co.kr/view/?no=20241230085447'],
 ['환경부, 순환경제 신기술·서비스 9건 규제박스 특례',
  'https://zdnet.co.kr/view/?no=20241226154137'],
 ["스마트카라, '나폴리 맛피아'와 쿠킹 클래스", 'https://zdnet.co.kr/view/?no=20241220193857'],
 ['스마트카라, 음식물처리기 보상판매…최대 54만원 할인',
  'https://zdnet.co.kr/view/?no=20241210232634'],
 ['제4회 팩트체크 전국대회 시상식 열려...총 15점 수상',
  'https://zdnet.co.kr/view/?no=20241208102041'],
 ['쿠쿠전자, 전자레인지 신제품 출시', 'https://zdnet.co.kr/view/?no=20241205114605'],
 ['휴롬, 연말 프로모션…착즙기 최대 26% 할인', 'https://zdnet.co.kr/view/?no=20241129173530'],
 ['산정특례 적용 희귀질환 1314개로 늘어…‘이완불능증’ 등 66개 추가',
  'https://zdnet.co.kr/view/?no=20241129002715'],
 ['익히지 않은 어패류에서 노로바이러스 식중독 발생 우려',
  'https://zdnet.co.kr/view/?no=20241122173007'],
 ['케이블TV協, 3분기 지역채널 우수프로 8편 선정',
  'https://zdnet.co.kr/view/?no=20241120132906'],
 ['"요리해줘" 한 마디면 끝…삼성이 꿈꾸는 미래 식생활',
  'https://zdnet.co.kr/view/?no=20241119161715'],
 ['누비랩, CES 2025 디지털 헬스 혁신상', 'https://zdnet.co.kr/view/?no=20241115172948'],
 ["삼성전자, 국내 가전업계 최초 '당일 배송·설치' 서비스 시작",
  'https://zdnet.co.kr/view/?no=20241113082353'],
 ["SK하이닉스 '물길봉사대', 경기 남부 하천 정화 봉사활동",
  'https://zdnet.co.kr/view/?no=20241112094650'],
 ['이롭 음식물처리기, 백화점 14곳 입점', 'https://zdnet.co.kr/view/?no=20241111170209'],
 ["스마트카라, '나폴리 맛피아' 쿠킹 클래스 모집", 'https://zdnet.co.kr/view/?no=20241107101852'],
 ['신일, 정경호와 로봇청소기 광고 공개', 'https://zdnet.co.kr/view/?no=20241016212046'],
 ['한종희 "삼성, 스마트홈 리더십 100년까지 이어갈 것"',
  'http://zdnet.co.kr/view/?no=20250104015036'],
 ["AI 드론에 배터리 교체·냉각까지…세계가 주목한 韓 '드론 스테이션'",
  'http://zdnet.co.kr/view/?no=20250107005122'],
 ['LG전자, 4분기 영업익 시장하회…연매출 87조원 사상최대 전망',
  'http://zdnet.co.kr/view/?no=20250106150953'],
 ['MS와 손잡은 LG전자, 공감지능 더 강력해진다', 'http://zdnet.co.kr/view/?no=20250106120252']]

In [53]:
len(data_list)

4

In [49]:
# 위 코드의 url을 보면 뒷 부분에 qurey = ~~~ 가 있음
# 이걸 활용해서 코드의 재사용성을 높임 
search_url = "https://search.zdnet.co.kr/"

all_df = pd.DataFrame(columns =['제목','주소'])

# params를 이용해서 결과 뽑음 
# 위 코드와 동일

for i in range (1,20):
    res = req.get(search_url, params ={'kwd' : "음식물", 'pageno':f'{i}'})
    html = bs(res.text, "lxml")

    # 뉴스 리스트 뽑아오기
    news_list = html.select("div.assetText > a")


    # 그걸 바탕으로 a링크의 href 주소를 저장
    a_list =[]
    for h in news_list:
        a_list.append(h.get("href"))


    # 가져온 것의 제목, 주소 저장
    data_list =[]
    
    for href in a_list:
        res2 = req.get(href)
        html2 = bs(res2.text, "lxml")
    
        # title과 href
        title = html2.select_one("div.news_head > h1").text
        data_list.append([title, href])

    df = pd.DataFrame(data_list, columns =['제목', '주소'])
    all_df = pd.concat([all_df, df])

In [53]:
all_df

,제목,주소
0,"[1분건강] 백신없는 노로바이러스감염증, 손씻기가 최선 예방법",https://zdnet.co.kr/view/?no=20250107103541
1,"쿠쿠, 12개 품목 'E-순환우수제품' 인증",https://zdnet.co.kr/view/?no=20250106101226
2,"7일 개막 CES 핵심 키워드는...""AI 세상으로 몰입하세요""",https://zdnet.co.kr/view/?no=20250102172215
3,"LG전자, CES 2025서 프리미엄 가전 '시그니처' 신제품 공개",https://zdnet.co.kr/view/?no=20241230085447
4,"환경부, 순환경제 신기술·서비스 9건 규제박스 특례",https://zdnet.co.kr/view/?no=20241226154137
...,...,...
3,"MS와 손잡은 LG전자, 공감지능 더 강력해진다",http://zdnet.co.kr/view/?no=20250106120252
0,"한종희 ""삼성, 스마트홈 리더십 100년까지 이어갈 것""",http://zdnet.co.kr/view/?no=20250104015036
1,AI 드론에 배터리 교체·냉각까지…세계가 주목한 韓 '드론 스테이션',http://zdnet.co.kr/view/?no=20250107005122
2,"LG전자, 4분기 영업익 시장하회…연매출 87조원 사상최대 전망",http://zdnet.co.kr/view/?no=20250106150953
3,"MS와 손잡은 LG전자, 공감지능 더 강력해진다",http://zdnet.co.kr/view/?no=20250106120252

In [55]:
all_df['제목'].value_counts()

제목
AI 드론에 배터리 교체·냉각까지…세계가 주목한 韓 '드론 스테이션'    19
LG전자, 4분기 영업익 시장하회…연매출 87조원 사상최대 전망       19
MS와 손잡은 LG전자, 공감지능 더 강력해진다                19
한종희 "삼성, 스마트홈 리더십 100년까지 이어갈 것"           19
국내 첫 소장이식 생존 20년 기록, 장기이식 역사 새 희망 쓰다       1
                                          ..
역대 최장 열대야에 여름가전 완판 행렬                      1
지마켓·옥션, '한가위 빅세일'...선물세트·인기브랜드 할인          1
신일 "전기 그릴팬 인기…추석 앞두고 수요 급증"                1
LG전자, IFA 2024서 공감지능 'AI홈 솔루션' 선봬          1
스마트카라, 신년 맞이 음식물처리기 프로모션                   1
Name: count, Length: 144, dtype: int64

In [57]:
all_df.drop_duplicates(subset='제목')

,제목,주소
0,"[1분건강] 백신없는 노로바이러스감염증, 손씻기가 최선 예방법",https://zdnet.co.kr/view/?no=20250107103541
1,"쿠쿠, 12개 품목 'E-순환우수제품' 인증",https://zdnet.co.kr/view/?no=20250106101226
2,"7일 개막 CES 핵심 키워드는...""AI 세상으로 몰입하세요""",https://zdnet.co.kr/view/?no=20250102172215
3,"LG전자, CES 2025서 프리미엄 가전 '시그니처' 신제품 공개",https://zdnet.co.kr/view/?no=20241230085447
4,"환경부, 순환경제 신기술·서비스 9건 규제박스 특례",https://zdnet.co.kr/view/?no=20241226154137
...,...,...
15,"SK매직, 원코크 얼음물 정수기 등 3개 제품 'CES 2024' 혁신상",https://zdnet.co.kr/view/?no=20240110180414
16,"쿠첸, 1.5L '초고속 파워 블렌더' 출시",https://zdnet.co.kr/view/?no=20240109180309
17,"현대차, 넥쏘 후속 모델 2025년 출시…수소 대전환 '고삐'",https://zdnet.co.kr/view/?no=20240109102238
18,"다쏘시스템, 'CES 2024'서 인체 버추얼 트윈 소개",https://zdnet.co.kr/view/?no=20240108090516
19,"스마트카라, 신년 맞이 음식물처리기 프로모션",https://zdnet.co.kr/view/?no=20240103193421

In [59]:
news_posts = []
 
for i in tqdm(range(1,21)):
    # 1~20 페이지까지 돌아가는 url 설정
    url = f"https://search.zdnet.co.kr/?kwd=%EC%9D%8C%EC%8B%9D%EB%AC%BC&area=&pageno={i}&term="  # f로 포멧해주기
    # https://search.zdnet.co.kr/?kwd=%EC%9D%8C%EC%8B%9D%EB%AC%BC&area=&pageno=3&term=
    res = req.get(url)
    html = bs(res.text, "lxml")
 
    titles = html.select("div.assetText > a > h3")
    aTags = html.select("section.news_box div.assetText > a")
 
    for i in range(len(titles)):
        news_posts.append([titles[i].text, aTags[i].get("href")])
 
    time.sleep(1.5)

NameError: name 'tqdm' is not defined